[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'


[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme jellybeans
'''
[[plugins]]
repo = 'powerline/powerline'
