# main
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

# syntax

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# 視覚系
repo = 'nathanaelkane/vim-indent-guides'

# 闇の力
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/denite.nvim'
